Repository bcgov/jag-ai-reviewer, pull requests merged in 2021-05, with the labels that each got.

#16 Migrating test code
  .gitignore
  test/.gitignore
  test/README.md
  test/pom.xml
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/Keys.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/RunCucumberTest.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/TestConfig.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/bdd/CucumberHooks.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/config/BrowserScope.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/config/BrowserScopePostProcessor.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/error/EfilingTestException.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/helpers/SubmissionHelper.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/page/AiReviewerAdminClientPage.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/page/BasePage.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/services/DocumentTypeConfigService.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/services/ExtractDocumentService.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/ConfigureDocumentTypesInAiReviewerAdminSD.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/ConfigureDocumentTypesSD.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/ConfigureRestrictedDocumentedTypesSD.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/ExtractValidatedDocumentsSD.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/GetProcessedDocumentSD.java
  test/src/test/resources/data/test-invalid-document.pdf
  test/src/test/resources/data/test-rcc-document.pdf
  test/src/test/resources/data/test-valid-document.pdf
  test/src/test/resources/extent-config.xml
  test/src/test/resources/extent.properties
  test/src/test/resources/features/configureDocumentTypesInAiReviewerAdmin.feature
  test/src/test/resources/features/configureRestrictedDocumentTypes.feature
  test/src/test/resources/features/configuredDocumentTypes.feature
  test/src/test/resources/features/extractValidatedDocuments.feature
  test/src/test/resources/features/getProcessedDocument.feature
  test/src/test/resources/log4j2.properties
  test/src/test/resources/payload/additional-restricted-document-type-payload.json
  test/src/test/resources/payload/document-type-config-payload.json
  test/src/test/resources/payload/document-type-config-update-payload.json
  test/src/test/resources/payload/restricted-document-type-payload.json
  test/src/test/resources/payload/restricted-document-type-update-payload.json
Labels: QA

#19 Cucumber test workflow migration
  .github/workflows/cucumber-test.yml
  test/README.md
  test/docker-compose-integration.yml
Labels: QA

#44 Add postman collection
  src/backend/ai-reviewer-cso-api/src/test/jag-reviewer-cso-api.postman_collection.json
Labels: :racing_car:, :train::train::train::train:, It's Working, indeed, porkchopsandwiches

#34 Cucumber workflow integration
  .env
  .github/workflows/cucumber-test.yml
  .gitignore
  docker-compose.yml
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/ConfigureDocumentTypesInAiReviewerAdminSD.java
Labels: It's Working, QA

#52 Renamed files from Efiling to Ai reviewer
  .env
  .gitignore
  test/.gitignore
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/error/AiReviewerTestException.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/error/EfilingTestException.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/services/DocumentTypeConfigService.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/services/ExtractDocumentService.java
Labels: QA

#48 add array functionality
  src/backend/libs/ai-diligen-client/src/main/java/ca/bc/gov/open/jag/aidiligenclient/diligen/processor/FieldProcessorImpl.java
Labels: :racing_car:, :train::train::train::train:, It's Working, java, porkchopsandwiches

#56 Add badges
  .gitignore
  README.md
Labels: QA

#58 Testing failing badge status
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/ConfigureDocumentTypesInAiReviewerAdminSD.java
Labels: QA

#59 Revert code after badge test
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/ConfigureDocumentTypesInAiReviewerAdminSD.java
Labels: QA

#60 Bug fixes
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/Keys.java
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/document/DocumentsApiDelegateImpl.java
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/webhook/WebHookService.java
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/webhook/WebHookServiceImpl.java
  src/backend/ai-reviewer-api/src/test/java/ca/bc/gov/open/jag/aireviewerapi/document/documentsApiDelegateImpl/DocumentEventTest.java
  src/backend/ai-reviewer-api/src/test/java/ca/bc/gov/open/jag/aireviewerapi/document/documentsApiDelegateImpl/DocumentWebhookEventTest.java
  src/backend/ai-reviewer-api/src/test/java/ca/bc/gov/open/jag/aireviewerapi/webhook/WebHookServiceImplTest.java
  src/backend/ai-reviewer-cso-api/src/main/java/ca/bc/gov/open/jag/aireviewercsoapi/service/ProcessedDocumentServiceImpl.java
  src/backend/ai-reviewer-mock-api/src/main/java/ca/bc/gov/open/jag/aireviewermockapi/controller/ParentController.java
Labels: :racing_car:, :train::train::train::train:, It's Working, java, porkchopsandwiches

#61 Remove dependency on hard coded int
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/Keys.java
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/document/DocumentsApiDelegateImpl.java
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/document/validators/DocumentValidator.java
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/document/validators/DocumentValidatorImpl.java
  src/backend/ai-reviewer-api/src/test/java/ca/bc/gov/open/jag/aireviewerapi/document/validators/documentValidator/ValidateExtractedDocumentTest.java
  src/backend/libs/ai-diligen-client/src/main/java/ca/bc/gov/open/jag/aidiligenclient/diligen/processor/FieldProcessorImpl.java
Labels: :racing_car:, :train::train::train::train:, java, porkchopsandwiches

#66 CSO API extract notification test
  .github/workflows/cucumber-test.yml
  test/docker-compose-integration.yml
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/Keys.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/TestConfig.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/services/ExtractNotificationService.java
  test/src/test/java/ca/bc/gov/open/jag/ai/reviewer/stepDefinitions/ExtractNotificationFromCsoApiSD.java
  test/src/test/resources/features/extractNotificationFromCsoApi.feature
  test/src/test/resources/payload/extract-notification-payload.json
Labels: QA

#74 Add file sizing configuration
  src/backend/ai-reviewer-api/src/main/resources/application.yml
Labels: :racing_car:, :train::train::train::train:, It's Working, porkchopsandwiches

#79 Remove party validation
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/Keys.java
  src/backend/ai-reviewer-api/src/main/java/ca/bc/gov/open/jag/aireviewerapi/document/validators/DocumentValidatorImpl.java
  src/backend/ai-reviewer-api/src/main/resources/courtDetails.schema.json
  src/backend/ai-reviewer-api/src/test/java/ca/bc/gov/open/jag/aireviewerapi/document/validators/documentValidator/ValidateExtractedDocumentTest.java
Labels: :racing_car:, :train::train::train::train:, It's Working, java, porkchopsandwiches
